# Generated by Django 5.2 on 2026-03-26 17:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=12, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('image', models.ImageField(blank=True, null=True, upload_to='landmarks/', verbose_name='Imagem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
                ('type', models.CharField(choices=[('BASIC', 'Farmácia Municipal'), ('SPECIALIZED', 'Farmácia Estadual'), ('POPULAR', 'Farmácia Popular')], default='BASIC', max_length=20, verbose_name='Tipo')),
                ('address', models.CharField(max_length=200, verbose_name='Endereço')),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.landmark', verbose_name='Localização no Mapa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
