# Generated by Django 5.2 on 2026-03-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landmark',
            options={'ordering': ('name', '-created_at'), 'verbose_name': 'Ponto de Referência', 'verbose_name_plural': 'Pontos de Referência'},
        ),
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'ordering': ('name', '-created_at'), 'verbose_name': 'Farmácia', 'verbose_name_plural': 'Farmácias'},
        ),
        migrations.AlterField(
            model_name='landmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em:'),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em:'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em:'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em:'),
        ),
    ]
