# Generated by Django 5.2 on 2026-03-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
                ('code', models.CharField(max_length=5, verbose_name='Código do CID')),
                ('documents', models.ManyToManyField(to='medications.document', verbose_name='Documentos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generic_name', models.CharField(max_length=255, verbose_name='Nome genérico')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
                ('concentration', models.CharField(max_length=255, verbose_name='Concentração')),
                ('components', models.CharField(max_length=255, verbose_name='Componentes')),
                ('cids', models.ManyToManyField(blank=True, to='medications.cid', verbose_name='CID')),
                ('documents', models.ManyToManyField(blank=True, to='medications.document', verbose_name='Documentos')),
                ('pharmacies', models.ManyToManyField(to='map.pharmacy', verbose_name='Farmácias')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
