# Generated by Django 5.2 on 2026-03-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cid',
            options={'ordering': ('name', '-created_at'), 'verbose_name': 'CID', 'verbose_name_plural': "CID's"},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('name', '-created_at'), 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ('generic_name', '-created_at'), 'verbose_name': 'Medicação', 'verbose_name_plural': 'Medicações'},
        ),
        migrations.AlterField(
            model_name='cid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em:'),
        ),
        migrations.AlterField(
            model_name='cid',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em:'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em:'),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em:'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em:'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em:'),
        ),
    ]
