# Generated by Django 5.2 on 2026-03-31 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_alter_cid_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='components',
        ),
    ]
