# Generated by Django 5.2 on 2026-03-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_remove_pharmacy_landmark_pharmacy_latitude_and_more'),
        ('medications', '0003_remove_medication_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='concentration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Concentração'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='pharmacies',
            field=models.ManyToManyField(blank=True, to='map.pharmacy', verbose_name='Farmácias'),
        ),
    ]
