# Generated by Django 5.2 on 2026-04-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_alter_medication_concentration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='type',
            field=models.CharField(choices=[('BASIC', 'Básico'), ('SPECIALIZED', 'Especializado'), ('POPULAR', 'Popular')], default='BASIC', max_length=20, verbose_name='Tipo'),
        ),
    ]
